# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Run all unit tests"
  lane :run_unit_tests do
    UI.message("Running unit tests for Debug variant 🚀")
    gradle(
      task: "testDebugUnitTest",
      flags: "--parallel --daemon"
    )
  end
end
